### ISSUE TITLE
How to deal with checkboxes

### ISSUE THREAD

**Issue by daguar** [codeforamerica/typeseam#11]
I've been thinking about this so figured I'd open an issue for discussion.

There seem to be two types of checkboxes:
1. One where "yes/no" maps cleanly to a **single checkbox** being checked or not
2. One where "yes/no" maps to **checking one of two possible checkboxes**

The (1) case is fairly straightforward, but (2) is trickier.

To deal with this, one might 

I've also been thinking that more generally a user could always have access to a lambda/closure that has (a) all inputs and (b) PDF fields available to allow for custom field hackery.

For illustration, here's an example:
```python
def additional_custom_writing_for_pdf_after_initial_population(input_data_dict, pdf_fields_with_initial_values_dict):
    if input_data_dict['user_said_to_mark_all_checkbox_questions_yes']:
        pdf_field_with_initial_values_dict['Checkbox 1'] = 'yes'
        pdf_field_with_initial_values_dict['Checkbox 2'] = 'yes'
        pdf_field_with_initial_values_dict['Checkbox 3'] = 'yes'
```

**Comment by bengolder** [comment]
Thanks @daguar. I'm going to set this issue aside for the moment and target it for a later release, because the awesome pdf-filling configuration process we've been discussing isn't really needed until later down the road.

**Comment by daguar** [comment]
For sure - I only opened the issue for discussion (labeled it "question" to signify) - no worries!

**Comment by bengolder** [comment]
Now that I have a branch that is parsing pdfs with pdftk, it would be useful to isolate some test cases with sample pdfs for this issue.

**Comment by bengolder** [comment]
@daguar I like your proposal. I think a nice internal hook for custom post transformation is a great idea. In the Typeform to Seamless docs code, I created a [field translation object](https://github.com/codeforamerica/typeseam/blob/master/data/translator.py) with [associated processors](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/form_field_processors.py), a similar but not as versatile method.

For this particular case of dealing with different checkboxes, it also seems possible that an API consumer could POST JSON data that names multiple fields as mutually exclusive.
```
"radio_fields": [
    "Checkbox 1",
    "Checkbox 2",
    "Checkbox 3",
]
```
