### ISSUE TITLE
port project to Django and deprecate repo

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/typeseam#114]
This working prototype in Flask should be replaced by a more production-ready Django implementation. This will help address several small impediments and features (many of which are dealt with by Django out of the box).

**Comment by tmaybe** [comment]
Can you give more detail on what impediments and features this will address? I know internationalization is one of them...

**Comment by bengolder** [comment]
@tmaybe sure!

While there are some details this helps with, the overall reasoning is that if I'm making an app that has user accounts, internationalization, and is mostly CRUD-oriented, then Django is a better fit for the task than Flask. In the case of the repo, right now is probably the best time to proactively address refactoring, _before_ building out features and _after_ the use case has been validated and users acquired (moving from a working prototype to a beta).

Here's some of the features this might help:
- *Any further development of user accounts.* Django comes with role-based authentication and permissions built in, which we will likely want if we plan to support multiple counties in the same web app.
- #109. Django implements access logs for their built-in admin, which may be useful as a starting point.
- #75 & #76. The current app needs significant clean up to prune deprecated uses. This can be addressed by rewriting around the core validated use case.
- #78. As mentioned before, internationalization is currently stalled due to conflicts with 3rd party flask libraries. Django is built with internationalization in mind and would deprecate the use of those 3rd party libraries.
- #98. Django has more mature [form handling libraries that are proven to work well with Django's core](https://github.com/django/django-formtools/), and which cover many common CRUD implementations, including splitting a form across multiple views.

**Comment by bengolder** [comment]
This is still in process, but I'm going to close this issue and replace it with more specific incremental tasks.
