### ISSUE TITLE
fill out a CR-180 form as well

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/typeseam#14]
The CR-180 form will have its own Seamlessdocs document and TypeForm form

**Comment by bengolder** [comment]
Just thinking through the processes of adding new Typeforms and fillable pdfs:


#### Adding a new Typeform

1. Create an actual Typeform on https://admin.typeform.com
2. pull the fields from the Typeform (this could use a script that dumps to stdout) so you can see the keys and descriptors it is using.
3. Write a [translator, similar to this](https://github.com/codeforamerica/typeseam/blob/master/data/translator.py).
4. Build up a json fixture for the Typeform.
5. Load the new Typeform record using the json fixture.

**Comment by bengolder** [comment]
Looking at my version running locally, the `SeamlessDoc` table is not currently storing any objects. In other words, the model is unused:

```
lass SeamlessDoc(db.Model):
    __tablename__ = 'form_filler_seamlessdoc'
    id = db.Column(db.Integer, primary_key=True, index=True)
    seamless_key = db.Column(db.String(64))
    user_id = db.Column(db.Integer, db.ForeignKey('auth_user.id'))
    typeform_id = db.Column(
        db.Integer, db.ForeignKey('form_filler_typeform.id'))

    def __repr__(self):
        return '<SeamlessDoc:"{}">'.format(self.seamless_key)
```

**Comment by bengolder** [comment]
Here are the steps, as I see them, to prepare the app for adding a new form:

1. make a script for getting the fields of a Typeform
2. make a script for getting the fields of a SeamlessDoc
3. make a script for adding a new Typeform from a JSON fixture
4. make a script for adding a new SeamlessDoc from a JSON fixture
5. move the `seamless_id` field to the Typeform.
6. edit `form_filler.views`, `.tasks`, and `.queries` to look up the seamless doc in the right place.
