### ISSUE TITLE
make a non-typeform intake form

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/typeseam#56]
Advantages are few, problems are many (hard to edit footer, header, no translation, storing data in unnecessary places)

**Comment by tmaybe** [comment]
Maybe look at whatever framework/css library JAD used for their appointment rescheduling form?

**Comment by bengolder** [comment]
@alanjosephwilliams ?

**Comment by bengolder** [comment]
Remaining tasks necessary for shipping:
- [ ] match privacy policy page styling
- [ ] add thank you page content
- [ ] add consent button content

Other improvements:
- [ ] edit mailing address to be more readable
- [ ] add footer
- [ ] add conditional question display

**Comment by alanjosephwilliams** [comment]
@bengolder sorry for missing this earlier mention — non-essential things went unanswered this past week. What did you go with in terms of a frontend library and preprocessing?
