### ISSUE TITLE
Add faces names and titles to the page

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/typeseam#67]

**Comment by jazmynlatimer** [comment]
<img width="1381" alt="screen shot 2016-04-26 at 6 37 45 pm" src="https://cloud.githubusercontent.com/assets/5255453/14839228/06a80ff2-0bde-11e6-9e6c-8a94f0f8a6f8.png">

**Comment by jazmynlatimer** [comment]
<img width="1410" alt="screen shot 2016-04-27 at 3 14 15 pm" src="https://cloud.githubusercontent.com/assets/5255453/14869790/bfe99d44-0c8a-11e6-97c8-5fb5fbdbbc4f.png">
