### ISSUE TITLE
Add eligibility information

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/typeseam#71]

**Comment by jazmynlatimer** [comment]
<img width="1378" alt="screen shot 2016-04-26 at 6 32 52 pm" src="https://cloud.githubusercontent.com/assets/5255453/14839182/af028552-0bdd-11e6-9162-00e6d8727ce6.png">
<img width="1286" alt="screen shot 2016-04-26 at 6 32 59 pm" src="https://cloud.githubusercontent.com/assets/5255453/14839185/b45f9486-0bdd-11e6-957a-0bd6fd0d6010.png">

**Comment by jazmynlatimer** [comment]
<img width="393" alt="screen shot 2016-04-26 at 6 36 16 pm" src="https://cloud.githubusercontent.com/assets/5255453/14839200/d0aabd0a-0bdd-11e6-8a51-37e0b590109d.png">
<img width="394" alt="screen shot 2016-04-26 at 6 36 23 pm" src="https://cloud.githubusercontent.com/assets/5255453/14839205/d368e378-0bdd-11e6-9836-0229f232855c.png">
